try:
    print(n)
except Exception as e:
    print(e) 